# (Github Dark Tritanopia) Colors for Alacritty
# from https://github.com/nyoom-engineering/oxocarbon-alacritty/blob/main/oxocarbon-dark.yml

# Default colors
[colors.primary]
background = '#161616'
foreground = '#ffffff'

# Cursor colors
[colors.cursor]
text = '#0d1117'
cursor = '#c9d1d9'

# Normal colors
[colors.normal]
black = '#262626'
magenta = "#ff7eb6"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
red = "#ee5396"
cyan = "#3ddbd9"
white = "#dde1e6"

# Bright colors
[colors.bright]
black = '#393939'
red = '#ee5396'
green = '#42be65'
yellow = '#ffe97b'
blue = '#33b1ff'
magenta = '#ff7eb6'
cyan = '#3ddbd9'
white = '#ffffff'
